### ISSUE TITLE
Bootstrap Overriding Non-Bootstrap Theme's Rules.

### ISSUE THREAD

**Issue by skrantzman** [2sic/2sxc-content-app#19]
If using a non-Bootstrap theme, but your theme's CSS framework uses similar rules, those rule are overridden by some of the Bootstrap rules that contain !important.  You can see from the below screenshot how a `.bg-primary` rule with a higher priority is being overridden by `.bg-primary` rule of lower priority but has **!important.** This rule is coming from Bootstrap's `_background-varient.css file`.

![image](https://user-images.githubusercontent.com/7874652/108782667-da7d9a80-7520-11eb-8246-cb3702729f48.png)

I believe that the `_backgorund-varient.css` file is being called/imported by `stackpath.bootstrapcdn...`  which in turn is being referenced in `\Portals\0\2sxc\Content\.data\app.xml`

I would expect that the bootstrapcdn not be called/loaded when the site's/pages's theme does not use Bootstrap as the CSS framework.

EDIT: FYI, I am creating Tailwind 2.0 (tlw2) version of the default 2sxsc content templates to contribute to 2sxc based on this conversation: https://github.com/DNN-Connect/connect.koi/issues/13 

EDIT 2: Attached a Tailwind theme based on  Bootstrap 4 Instant theme, in case you need a tlw2 theme for testing.
[Tailwind 2 Instant_1.0.0_install.zip](https://github.com/2sic/2sxc-content-app/files/6026162/Tailwind.2.Instant_1.0.0_install.zip)

**Comment by iJungleboy** [comment]
Hi @skrantzman 

The logic is as follows: if the skin is BS3 or BS4, then the content will load the appropriate template and include no CSS frameworks, as the styling has been optimized for this. 

If it's another framework or unknown, then it includes BS4 from the CDN to ensure that the parts look correct. This is important so people giving the content-templates a try see something realistic, and not just a strange looking sequence of titles and images. 

If you want to use another CSS framework, you can easily turn this off and modify the templates to your needs. Just look at https://github.com/2sic/2sxc-content-app/blob/master/shared/_Assets.cshtml#L8

This says that if it's not bootstrap 4, it will load the CSS specified in App Settings. You can either disable this line, or change what should be loaded in the app settings.

**Comment by skrantzman** [comment]
iJungleboy,

Before makiing the original post, I first changed the statement to check if the theme's framework is Tailwind.. `@if(!Koi.Is("tlw2))`, as I assumed this reads _"If Koi Is Not tlw2, then load bootstrap"._  This did not work. Next, I commented out that line in` ../2sxc/Content/tlw2/shared/_Assets.cshtml`, but it did not stop Bootstrap from loading. Thinking maybe that the _Assets.cshtml file in `../2sxc/Content/Shared` might be causing the problem, I commented out that line as well, but it also had no effect on Bootstrap loading.  After reading your reply, I went into App Settings and removed the Bootstrap reference, which did have the desired effect.  I could be wrong, but it appears that App.Settings.Assets is still loading regardless of the _Assest.cshtml file.

**Comment by iJungleboy** [comment]
my guess is you were in the wrong `_Assets.cshtml` file - as there is one for BS3 and for BS4, and maybe you also created your own.

**Comment by skrantzman** [comment]
Turns out it was the instance of DNN which was a relatively new install. I created a new instance of DNN 9.8.1 and installed both my theme, and tlw2 content templates and it works correctly now.

**Comment by iJungleboy** [comment]
perfect :)
