### ISSUE TITLE
Update the Installation Instructions for Updating?

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc-content-app#2]
https://github.com/2sic/2sxc-content-app/wiki/Installation-Instructions
 
If you have an older version of 2sxc and the Content App installed. You then easily upgrade 2sxc the normal way. But how would you "upgrade" the Content App to the latest version?

**Comment by iJungleboy** [comment]
There is now quick way to do this, since these templates have usually been customized to your needs and site look & feel. So this is a template to get started, but you can't really update your document with another template.

**Comment by jeremy-farrance** [comment]
We actually leave the base templates alone in the 2sxc/Content/ folder, all our new work is done in a project subfolder, 2sxc/Content/ABBV. If we modify an original of yours, we make a copy to the subfolder and modify/use that. 
 
But yeah, I understand. So if I wanted I could at least copy over the templates in the root from the latest .zip of the Content App, right? Besides demo data/entities, there is nothing else in the install that the templates depend on?

**Comment by iJungleboy** [comment]
That will do most of the work. Depending on how old your previous version is, the content-types may have some fields added - which would be used in the template. You could also import these separately. Basically you would have to install the standard set in a new portal, then in app-export just export the types you want and over-import them them again in the target (all in the app-tab).
