### ISSUE TITLE
How to Upgrade the Content App

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc-content-app#31]
We have a project we just started last week. At install we had Dnn 9.10.1, 2sxc 11.22.1 LTS and the Content App 11.0.6.
 
We are pretty excited about 2sxc v12 and (did a backup then) installed that. But now how to we get the Content App from 11.0.6 to 12.latest? It was installed as part of our deploy process, but other than the 1 Content module, its completely not used at all, untouched, not a single CT record added, nothing modified/used at all. 
 
Is there a logical way to upgrade?
 
Is there a safe way to delete the 11.0.6 version of the Content App and then install 12.5.2?
 
If no and no, is there some way to instead install 12.5.2 and have it work side by side? 
 
I did reread [this](https://azing.org/2sxc/l/4j9cqpvC/content-app) and issue #8 but didn't find anything helpful.

**Comment by iJungleboy** [comment]
I must admit it's fairly complicated - sorry. 

I created a checklist which explains everything: https://azing.org/2sxc/r/Ll3AalkO

**Comment by jeremy-farrance** [comment]
Stunning and perfect, I cannot thank you enough!!

**Comment by iJungleboy** [comment]
You're welcome :). 

And thanks for being a fan and spreading the word!
