### ISSUE TITLE
Feature/Enh Request - Turn on/off alert message in Content - Image (header banners)

### ISSUE THREAD

**Issue by bmusgrove-accuraty** [2sic/2sxc-content-app#33]
I'm submitting a Content-Type feature request ...

**Current behavior**
When you select Content - Image and choose either _Banner Narrow (for headers_) OR _Banner - Wide (larger headers)_ it now comes with the alert message hardcoded in the template with no way to edit that message out of the box.

**Enhanced behavior**
When choosing either option above, it should be possible to turn the alert message on/off. In addition, one should be able to edit the text field for the alert right away.

Since these two views are under the Content-Type Image, I didn't expect to find text. However, I think the alert message is a wonderful addition to these header banners and that simply making them turn on/off would be nice.

Making a custom view per project seems redundant and with how quickly sometimes a Client/Content Manager needs certain alert messages on their website it would be a great feature for them to do without waiting for a developer to make a custom view and enter the alert message.

**My environment**
Content App - Version 13.1.0
DNN - 09.10.02

**Comment by bmusgrove-accuraty** [comment]
![chrome_FSTszwRIjX](https://user-images.githubusercontent.com/68243808/159782736-2f2b5086-b904-4a4f-9931-d2b440d158fb.png)

**Comment by iJungleboy** [comment]
@maaaximum pls check this - sounds like a mistake that is pretty useless. Pls check and remove.

@ropalko just fyi

@bmusgrove-accuraty this would be a mistake, it's not an intended feature, so we wouldn't expand this to also support alerts or something, that kind of functionality should be in a separate thing/app.

**Comment by bmusgrove-accuraty** [comment]
@iJungleboy Understood and not a problem at all. I knew it seemed a little unusual, so thought I'd share. Thanks!

**Comment by maaaximum-at-2sic** [comment]
@bmusgrove-accuraty thank you for reporting this bug. It has now been fixed in the [13.01.01 release](https://github.com/2sic/2sxc-content-app/releases/tag/v13.01.01).
