### ISSUE TITLE
Google Maps URLs are hardcoded for German, "hl=de"

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc-content-app#7]
The Views included for Google Maps in Content App have the "de" language hardcoded when building the Directions URL. See below.
 
```
... .Replace(" ", "+")+"&amp;saddr=&amp;f=d&amp;hl=de&amp;ie=UTF8&amp;z=16
                                                  ^^^
```

**Comment by iJungleboy** [comment]
We're currently working on a big new release which will be using all the latest features and best-practices of Bootstrap4, Koi and 2sxc 10+. 
We've already added a fix for this too, but it will be in that package, which will require 2sxc 10.20.
