### ISSUE TITLE
How to upgrade from Content App 3.03.00 to 10+ ?

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc-content-app#8]
I have a recently deployed project that started life with DNN 9.04.x, 2sxc 10.x, and Content App 3.03.00. The site is now running DNN 9.04.04 and 2sxc 10.24.
 
How do I upgrade the Content App to the new v10 release? We've already got a significant amount of content deploy, almost entirely using the Content App:
![image](https://user-images.githubusercontent.com/653301/71313092-9ca35480-23f9-11ea-8f98-5996a433a7d9.png)
 
If there is an automatic way, great. If not, can you outline the steps necessary to get there? Thanks in advance!!

**Comment by iJungleboy** [comment]
I'll try to write a guide soon.

**Comment by jeremy-farrance** [comment]
We now have 3 projects in this state. Any chance you can qualify soon so I can manage client expectations? Not really in any rush, but curious if 'soon' might means days or weeks. Thank you in advance.

**Comment by jeremy-farrance** [comment]
I am still interested in that guide. Does any part of it exist or is there some quick guidance anyone can give on what the steps are?

**Comment by iJungleboy** [comment]
This is not 100% done yet, but I have most of it prepared here, incl. special scenarios etc.

https://azing.org/2sxc/l/4j9cqpvC/content-app
